In [67]:
import pandas as pd
import sqlite3

In [68]:
house_data_to_load = "Resources/Suburb_HouseV2021A.csv"
house_data = pd.read_csv(house_data_to_load)
house_data.head(5)

,Suburb House Price - 2021,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,prelim 2022,change,change,Growth PA,NaN
1,locality,Median,Median,Median,Median,Median,Median,Median,Median,Median,Median,Median,Median,2020-2021,2011-2021,NaN,NaN
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABBOTSFORD,730000,714000,792500,862500,925000,1187500,1280000,1192500,1050000,1200000,1375000,1517500,15,88,6.5,NaN

In [69]:
house_data = house_data.drop(index=([0,1,2,3])).copy()
house_data.head(5)

,Suburb House Price - 2021,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
4,ABBOTSFORD,730000,714000,792500,862500,925000,1187500,1280000,1192500,1050000,1200000,1375000,1517500,15,88,6.5,NaN
5,ABERFELDIE,994000,852500,947500,1045000,1207500,1300000,1471000,1498500,1390000,1520000,1880500,1575000,24,89,6.6,NaN
6,AINTREE,-,-,-,-,600000,600000,571000,557500,575000,640000,719000,760000,12,NaN,NaN,NaN
7,AIREYS INLET,680000,634000,664000,625500,680000,715000,737500,869000,985000,1132500,1775000,1750000,57,161,10.1,NaN
8,AIRPORT WEST,557500,495000,532000,575000,635000,742000,845000,845000,795000,812500,960000,919500,18,72,5.6,NaN

In [70]:
house_data = house_data.rename(columns={'Suburb House  Price - 2021':'Suburb',
    'Unnamed: 1':'2011','Unnamed: 2':'2012','Unnamed: 3':'2013','Unnamed: 4':'2014','Unnamed: 5':'2015',
    'Unnamed: 6':'2016','Unnamed: 7':'2017','Unnamed: 8':'2018','Unnamed: 9':'2019','Unnamed: 10':'2020',
    'Unnamed: 11':'2021','Unnamed: 12':'2022','Unnamed: 13':'2020-2021','Unnamed: 14':'2011-2021',
    'Unnamed: 15':'Growth PA'} ).copy()
house_data.head(5)

,Suburb,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2020-2021,2011-2021,Growth PA,Unnamed: 16
4,ABBOTSFORD,730000,714000,792500,862500,925000,1187500,1280000,1192500,1050000,1200000,1375000,1517500,15,88,6.5,NaN
5,ABERFELDIE,994000,852500,947500,1045000,1207500,1300000,1471000,1498500,1390000,1520000,1880500,1575000,24,89,6.6,NaN
6,AINTREE,-,-,-,-,600000,600000,571000,557500,575000,640000,719000,760000,12,NaN,NaN,NaN
7,AIREYS INLET,680000,634000,664000,625500,680000,715000,737500,869000,985000,1132500,1775000,1750000,57,161,10.1,NaN
8,AIRPORT WEST,557500,495000,532000,575000,635000,742000,845000,845000,795000,812500,960000,919500,18,72,5.6,NaN

In [71]:
house_data = house_data.drop(columns=['Unnamed: 16']).copy()
house_data.head(5)

,Suburb,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2020-2021,2011-2021,Growth PA
4,ABBOTSFORD,730000,714000,792500,862500,925000,1187500,1280000,1192500,1050000,1200000,1375000,1517500,15,88,6.5
5,ABERFELDIE,994000,852500,947500,1045000,1207500,1300000,1471000,1498500,1390000,1520000,1880500,1575000,24,89,6.6
6,AINTREE,-,-,-,-,600000,600000,571000,557500,575000,640000,719000,760000,12,NaN,NaN
7,AIREYS INLET,680000,634000,664000,625500,680000,715000,737500,869000,985000,1132500,1775000,1750000,57,161,10.1
8,AIRPORT WEST,557500,495000,532000,575000,635000,742000,845000,845000,795000,812500,960000,919500,18,72,5.6

In [72]:
import numpy as np
house_data1 = house_data.replace('-',np.NaN).copy()
#house_data = house_data.replace('NA',np.NaN).copy() 

#house_data.loc[house_data['Suburb'] =='BEEAC']

In [73]:
for year in range(2011, 2022):
    column=f'{year}-{year+1}'

    house_data1[column]=round(house_data1.apply(lambda x:(float(x[f'{year+1}'])-float(x[f'{year}'])) / float(x[f'{year}']) * 100,axis=1),1)

In [74]:
house_data1

,Suburb,2011,2012,2013,2014,2015,2016,2017,2018,2019,...,2011-2012,2012-2013,2013-2014,2014-2015,2015-2016,2016-2017,2017-2018,2018-2019,2019-2020,2021-2022
4,ABBOTSFORD,730000,714000,792500,862500,925000,1187500,1280000,1192500,1050000,...,-2.2,11.0,8.8,7.2,28.4,7.8,-6.8,-11.9,14.3,10.4
5,ABERFELDIE,994000,852500,947500,1045000,1207500,1300000,1471000,1498500,1390000,...,-14.2,11.1,10.3,15.6,7.7,13.2,1.9,-7.2,9.4,-16.2
6,AINTREE,NaN,NaN,NaN,NaN,600000,600000,571000,557500,575000,...,NaN,NaN,NaN,NaN,0.0,-4.8,-2.4,3.1,11.3,5.7
7,AIREYS INLET,680000,634000,664000,625500,680000,715000,737500,869000,985000,...,-6.8,4.7,-5.8,8.7,5.1,3.1,17.8,13.3,15.0,-1.4
8,AIRPORT WEST,557500,495000,532000,575000,635000,742000,845000,845000,795000,...,-11.2,7.5,8.1,10.4,16.9,13.9,0.0,-5.9,2.2,-4.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819,YARRAM,195500,215000,190000,202500,245000,230000,225000,218000,240000,...,10.0,-11.6,6.6,21.0,-6.1,-2.2,-3.1,10.1,8.3,25.7
820,YARRAVILLE,607000,613000,696000,710000,810000,900500,1000000,1045000,971000,...,1.0,13.5,2.0,14.1,11.2,11.0,4.5,-7.1,6.1,13.9
821,YARRAWONGA,270000,300000,302500,297000,300500,320000,324500,345000,375000,...,11.1,0.8,-1.8,1.2,6.5,1.4,6.3,8.7,21.7,24.1
822,YEA,270000,255000,260000,255000,260000,305000,385000,390000,435500,...,-5.6,2.0,-1.9,2.0,17.3,26.2,1.3,11.7,-3.0,8.9
823,YINNAR,208000,221500,220000,240000,182500,230000,270000,245000,255000,...,6.5,-0.7,9.1,-24.0,26.0,17.4,-9.3,4.1,14.7,22.3

In [75]:
# Create Tables
conn = sqlite3.connect('static/data/house.sqlite')

c = conn.cursor()

c.execute('''DROP TABLE change;''')
c.execute('''DROP TABLE median_house;''')
""" c.execute('''CREATE TABLE year_period
       (year_period_id  CHAR(3) PRIMARY KEY     NOT NULL,
       NAME CHAR(50)    NOT NULL);''') """

c.execute('''CREATE TABLE change
       (suburb  CHAR(50) NOT NULL,
       period   char(50) NOT NULL,
       change_percent Numeric,
       primary key (suburb,period));''')

c.execute('''CREATE TABLE median_house
       (suburb  CHAR(50) NOT NULL,
       year integer NOT NULL,
       median Numeric,
       primary key (suburb,year));''')
print ("tables created")

tables created

In [76]:
for ind, row in house_data1.iterrows():
    # Insert into table median_house
    for year in range(2011, 2023):
        print(row['Suburb'],year, row[f'{year}'])
        if ( pd.notnull(row[f'{year}'])):
            SQL = f"INSERT INTO median_house (suburb,year,median) VALUES ( '{row['Suburb']}', {f'{year}'}, {row[f'{year}']} )"
            print(SQL)
            c.execute(SQL)
    # Insert into table change

    for period in ['2011-2021','Growth PA']:
        if ( pd.notnull(row[period])):
            SQL = f"INSERT INTO change (suburb,period,change_percent) VALUES ( '{row['Suburb']}', '{period}', {row[period]} )"
            print(SQL)
            c.execute(SQL)

    for year in range(2011,2022):
        column=f'{year}-{year+1}'
        if (pd.notnull(row[column])):
            SQL = f"INSERT INTO change (suburb,period,change_percent) VALUES ( '{row['Suburb']}', '{column}', {row[column]} )"
            print(SQL)
            c.execute(SQL)

ABBOTSFORD 2011 730000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2011, 730000 )
ABBOTSFORD 2012 714000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2012, 714000 )
ABBOTSFORD 2013 792500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2013, 792500 )
ABBOTSFORD 2014 862500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2014, 862500 )
ABBOTSFORD 2015 925000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2015, 925000 )
ABBOTSFORD 2016 1187500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2016, 1187500 )
ABBOTSFORD 2017 1280000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2017, 1280000 )
ABBOTSFORD 2018 1192500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2018, 1192500 )
ABBOTSFORD 2019 1050000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2019, 1050000 )
ABBOTSFORD 2020 1200000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2020, 1200000 )
ABBOTSFORD 2021 1375000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2021, 1375000 )
ABBOTSFORD 2022 1517500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABBOTSFORD', 2022, 1517500 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2011-2021', 88 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', 'Growth PA', 6.5 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2011-2012', -2.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2012-2013', 11.0 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2013-2014', 8.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2014-2015', 7.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2015-2016', 28.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2016-2017', 7.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2017-2018', -6.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2018-2019', -11.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2019-2020', 14.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2020-2021', 14.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABBOTSFORD', '2021-2022', 10.4 )
ABERFELDIE 2011 994000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2011, 994000 )
ABERFELDIE 2012 852500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2012, 852500 )
ABERFELDIE 2013 947500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2013, 947500 )
ABERFELDIE 2014 1045000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2014, 1045000 )
ABERFELDIE 2015 1207500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2015, 1207500 )
ABERFELDIE 2016 1300000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2016, 1300000 )
ABERFELDIE 2017 1471000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2017, 1471000 )
ABERFELDIE 2018 1498500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2018, 1498500 )
ABERFELDIE 2019 1390000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2019, 1390000 )
ABERFELDIE 2020 1520000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2020, 1520000 )
ABERFELDIE 2021 1880500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2021, 1880500 )
ABERFELDIE 2022 1575000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ABERFELDIE', 2022, 1575000 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2011-2021', 89 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', 'Growth PA', 6.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2011-2012', -14.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2012-2013', 11.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2013-2014', 10.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2014-2015', 15.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2015-2016', 7.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2016-2017', 13.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2017-2018', 1.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2018-2019', -7.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2019-2020', 9.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2020-2021', 23.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ABERFELDIE', '2021-2022', -16.2 )
AINTREE 2011 nan
AINTREE 2012 nan
AINTREE 2013 nan
AINTREE 2014 nan
AINTREE 2015 600000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2015, 600000 )
AINTREE 2016 600000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2016, 600000 )
AINTREE 2017 571000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2017, 571000 )
AINTREE 2018 557500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2018, 557500 )
AINTREE 2019 575000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2019, 575000 )
AINTREE 2020 640000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2020, 640000 )
AINTREE 2021 719000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2021, 719000 )
AINTREE 2022 760000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AINTREE', 2022, 760000 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2015-2016', 0.0 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2016-2017', -4.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2017-2018', -2.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2018-2019', 3.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2019-2020', 11.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2020-2021', 12.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AINTREE', '2021-2022', 5.7 )
AIREYS INLET 2011 680000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2011, 680000 )
AIREYS INLET 2012 634000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2012, 634000 )
AIREYS INLET 2013 664000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2013, 664000 )
AIREYS INLET 2014 625500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2014, 625500 )
AIREYS INLET 2015 680000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2015, 680000 )
AIREYS INLET 2016 715000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2016, 715000 )
AIREYS INLET 2017 737500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2017, 737500 )
AIREYS INLET 2018 869000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2018, 869000 )
AIREYS INLET 2019 985000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2019, 985000 )
AIREYS INLET 2020 1132500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2020, 1132500 )
AIREYS INLET 2021 1775000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2021, 1775000 )
AIREYS INLET 2022 1750000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIREYS INLET', 2022, 1750000 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2011-2021', 161 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', 'Growth PA', 10.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2011-2012', -6.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2012-2013', 4.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2013-2014', -5.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2014-2015', 8.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2015-2016', 5.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2016-2017', 3.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2017-2018', 17.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2018-2019', 13.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2019-2020', 15.0 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2020-2021', 56.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIREYS INLET', '2021-2022', -1.4 )
AIRPORT WEST 2011 557500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2011, 557500 )
AIRPORT WEST 2012 495000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2012, 495000 )
AIRPORT WEST 2013 532000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2013, 532000 )
AIRPORT WEST 2014 575000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2014, 575000 )
AIRPORT WEST 2015 635000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2015, 635000 )
AIRPORT WEST 2016 742000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2016, 742000 )
AIRPORT WEST 2017 845000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2017, 845000 )
AIRPORT WEST 2018 845000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2018, 845000 )
AIRPORT WEST 2019 795000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2019, 795000 )
AIRPORT WEST 2020 812500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2020, 812500 )
AIRPORT WEST 2021 960000
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2021, 960000 )
AIRPORT WEST 2022 919500
INSERT INTO median_house (suburb,year,median) VALUES ( 'AIRPORT WEST', 2022, 919500 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2011-2021', 72 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', 'Growth PA', 5.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2011-2012', -11.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2012-2013', 7.5 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2013-2014', 8.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2014-2015', 10.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2015-2016', 16.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2016-2017', 13.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2017-2018', 0.0 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2018-2019', -5.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2019-2020', 2.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2020-2021', 18.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'AIRPORT WEST', '2021-2022', -4.2 )
ALBANVALE 2011 317000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2011, 317000 )
ALBANVALE 2012 310000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2012, 310000 )
ALBANVALE 2013 313000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2013, 313000 )
ALBANVALE 2014 328000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2014, 328000 )
ALBANVALE 2015 345000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2015, 345000 )
ALBANVALE 2016 439000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2016, 439000 )
ALBANVALE 2017 526500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2017, 526500 )
ALBANVALE 2018 546000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2018, 546000 )
ALBANVALE 2019 512000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2019, 512000 )
ALBANVALE 2020 545000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2020, 545000 )
ALBANVALE 2021 610000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2021, 610000 )
ALBANVALE 2022 605000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBANVALE', 2022, 605000 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2011-2021', 92 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', 'Growth PA', 6.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2011-2012', -2.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2012-2013', 1.0 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2013-2014', 4.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2014-2015', 5.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2015-2016', 27.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2016-2017', 19.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2017-2018', 3.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2018-2019', -6.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2019-2020', 6.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2020-2021', 11.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBANVALE', '2021-2022', -0.8 )
ALBERT PARK 2011 1390000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2011, 1390000 )
ALBERT PARK 2012 1270000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2012, 1270000 )
ALBERT PARK 2013 1360000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2013, 1360000 )
ALBERT PARK 2014 1503000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2014, 1503000 )
ALBERT PARK 2015 1700000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2015, 1700000 )
ALBERT PARK 2016 1775000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2016, 1775000 )
ALBERT PARK 2017 2150000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2017, 2150000 )
ALBERT PARK 2018 2070000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2018, 2070000 )
ALBERT PARK 2019 1990000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2019, 1990000 )
ALBERT PARK 2020 1895000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2020, 1895000 )
ALBERT PARK 2021 2300000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2021, 2300000 )
ALBERT PARK 2022 2076000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBERT PARK', 2022, 2076000 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2011-2021', 65 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', 'Growth PA', 5.2 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2011-2012', -8.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2012-2013', 7.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2013-2014', 10.5 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2014-2015', 13.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2015-2016', 4.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2016-2017', 21.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2017-2018', -3.7 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2018-2019', -3.9 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2019-2020', -4.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2020-2021', 21.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBERT PARK', '2021-2022', -9.7 )
ALBION 2011 400000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2011, 400000 )
ALBION 2012 379500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2012, 379500 )
ALBION 2013 379000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2013, 379000 )
ALBION 2014 432000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2014, 432000 )
ALBION 2015 481000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2015, 481000 )
ALBION 2016 593000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2016, 593000 )
ALBION 2017 730000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2017, 730000 )
ALBION 2018 755000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2018, 755000 )
ALBION 2019 675000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2019, 675000 )
ALBION 2020 727500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2020, 727500 )
ALBION 2021 830000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2021, 830000 )
ALBION 2022 785000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALBION', 2022, 785000 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2011-2021', 108 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', 'Growth PA', 7.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2011-2012', -5.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2012-2013', -0.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2013-2014', 14.0 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2014-2015', 11.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2015-2016', 23.3 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2016-2017', 23.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2017-2018', 3.4 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2018-2019', -10.6 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2019-2020', 7.8 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2020-2021', 14.1 )
INSERT INTO change (suburb,period,change_percent) VALUES ( 'ALBION', '2021-2022', -5.4 )
ALEXANDRA 2011 255000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2011, 255000 )
ALEXANDRA 2012 239000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2012, 239000 )
ALEXANDRA 2013 261000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2013, 261000 )
ALEXANDRA 2014 247500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2014, 247500 )
ALEXANDRA 2015 285000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2015, 285000 )
ALEXANDRA 2016 275000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2016, 275000 )
ALEXANDRA 2017 291500
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2017, 291500 )
ALEXANDRA 2018 335000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2018, 335000 )
ALEXANDRA 2019 325000
INSERT INTO median_house (suburb,year,median) VALUES ( 'ALEXANDRA', 2019, 325000 )
ALEXANDRA 2020 380000

In [77]:
conn.commit()
conn.close()